"""
Alembic environment for the timesheets module.

Auto-generated by ModuleRuntime. Uses per-module version table: alembic_timesheets.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

from runtime.models.base import Base

# Import module models so Alembic can detect them
from timesheets.models import (  # noqa: F401
    HourlyRate,
    TimeEntry,
    TimesheetApproval,
    TimesheetsSettings,
)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Per-module version table
VERSION_TABLE = "alembic_timesheets"


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (generate SQL)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        version_table=VERSION_TABLE,
        include_object=_include_timesheets_only,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (execute against DB)."""
    connectable = context.config.attributes.get("connection", None)
    if connectable is None:
        connectable = create_engine(
            config.get_main_option("sqlalchemy.url"),
            poolclass=pool.NullPool,
        )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table=VERSION_TABLE,
            include_object=_include_timesheets_only,
        )
        with context.begin_transaction():
            context.run_migrations()


def _include_timesheets_only(object, name, type_, reflected, compare_to):
    """Only include tables belonging to the timesheets module."""
    if type_ == "table":
        return name.startswith("timesheets_")
    return True


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
